Class {
	#name : #FamixTypeScriptUnknownSourceLanguage,
	#superclass : #FamixTypeScriptSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixTypeScriptSourceLanguage>
	<package: #FamixTypeScript>
	<generated>
	^self
]
