"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `concretizations` | `FamixTParametricAssociation` | `triggeringAssociation` | `FamixTConcretization` | The parameter concretizations associated with this association.|



"
Class {
	#name : 'FamixTypeScriptParametricReference',
	#superclass : 'FamixTypeScriptReference',
	#traits : 'FamixTParametricAssociation',
	#classTraits : 'FamixTParametricAssociation classTrait',
	#category : 'Famix-TypeScript-Entities-Entities',
	#package : 'Famix-TypeScript-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTypeScriptParametricReference class >> annotation [

	<FMClass: #ParametricReference super: #FamixTypeScriptReference>
	<package: #'Famix-TypeScript-Entities'>
	<generated>
]
