Class {
	#name : #FamixTypeScriptImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Famix-TypeScript-Entities'
}

{ #category : #testing }
FamixTypeScriptImportingContext >> importClass [
	<generated>
	^ self import: FamixTypeScriptClass
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importComment [
	<generated>
	^ self import: FamixTypeScriptComment
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importContainerEntity [
	<generated>
	^ self import: FamixTypeScriptContainerEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importEntity [
	<generated>
	^ self import: FamixTypeScriptEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importIndexedFileAnchor [
	<generated>
	^ self import: FamixTypeScriptIndexedFileAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importNamedEntity [
	<generated>
	^ self import: FamixTypeScriptNamedEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importNamespace [
	<generated>
	^ self import: FamixTypeScriptNamespace
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importSourceAnchor [
	<generated>
	^ self import: FamixTypeScriptSourceAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importSourceLanguage [
	<generated>
	^ self import: FamixTypeScriptSourceLanguage
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importSourceTextAnchor [
	<generated>
	^ self import: FamixTypeScriptSourceTextAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importSourcedEntity [
	<generated>
	^ self import: FamixTypeScriptSourcedEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importType [
	<generated>
	^ self import: FamixTypeScriptType
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importUnknownSourceLanguage [
	<generated>
	^ self import: FamixTypeScriptUnknownSourceLanguage
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportClass [
	<generated>
	^ self shouldImport: FamixTypeScriptClass
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportComment [
	<generated>
	^ self shouldImport: FamixTypeScriptComment
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportContainerEntity [
	<generated>
	^ self shouldImport: FamixTypeScriptContainerEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixTypeScriptEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportIndexedFileAnchor [
	<generated>
	^ self shouldImport: FamixTypeScriptIndexedFileAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportNamedEntity [
	<generated>
	^ self shouldImport: FamixTypeScriptNamedEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportNamespace [
	<generated>
	^ self shouldImport: FamixTypeScriptNamespace
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportSourceAnchor [
	<generated>
	^ self shouldImport: FamixTypeScriptSourceAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportSourceLanguage [
	<generated>
	^ self shouldImport: FamixTypeScriptSourceLanguage
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportSourceTextAnchor [
	<generated>
	^ self shouldImport: FamixTypeScriptSourceTextAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportSourcedEntity [
	<generated>
	^ self shouldImport: FamixTypeScriptSourcedEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportType [
	<generated>
	^ self shouldImport: FamixTypeScriptType
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportUnknownSourceLanguage [
	<generated>
	^ self shouldImport: FamixTypeScriptUnknownSourceLanguage
]
