"
I represent a TypeScript parametric arrow function.

## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `typeParameters` | `FamixTParametricEntity` | `genericEntity` | `FamixTTypeParameter` | The type parameters of this parametric entity. They can any type with the exception of primitive types|



"
Class {
	#name : 'FamixTypeScriptParametricArrowFunction',
	#superclass : 'FamixTypeScriptArrowFunction',
	#traits : 'FamixTParametricEntity',
	#classTraits : 'FamixTParametricEntity classTrait',
	#category : 'Famix-TypeScript-Entities-Entities',
	#package : 'Famix-TypeScript-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTypeScriptParametricArrowFunction class >> annotation [

	<FMClass: #ParametricArrowFunction super: #FamixTypeScriptArrowFunction>
	<package: #'Famix-TypeScript-Entities'>
	<generated>
]
