"
I represent a TypeScript Accessor (getter or setter)


"
Class {
	#name : 'FamixTypeScriptAccessor',
	#superclass : 'FamixTypeScriptMethod',
	#category : 'Famix-TypeScript-Entities-Entities',
	#package : 'Famix-TypeScript-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTypeScriptAccessor class >> annotation [

	<FMClass: #Accessor super: #FamixTypeScriptMethod>
	<package: #'Famix-TypeScript-Entities'>
	<generated>
]
