Class {
	#name : #FamixTypeScriptFileAnchor,
	#superclass : #FamixTypeScriptAbstractFileAnchor,
	#traits : 'FamixTFileNavigation',
	#classTraits : 'FamixTFileNavigation classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptFileAnchor class >> annotation [

	<FMClass: #FileAnchor super: #FamixTypeScriptAbstractFileAnchor>
	<package: #FamixTypeScript>
	<generated>
	^self
]
