Class {
	#name : #FamixTypeScriptCustomSourceLanguage,
	#superclass : #FamixTypeScriptSourceLanguage,
	#traits : 'FamixTNamedEntity',
	#classTraits : 'FamixTNamedEntity classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptCustomSourceLanguage class >> annotation [

	<FMClass: #CustomSourceLanguage super: #FamixTypeScriptSourceLanguage>
	<package: #FamixTypeScript>
	<generated>
	^self
]
