Class {
	#name : #FamixTypeScriptImportingContext,
	#superclass : #FmxImportingContext,
	#category : #'Famix-TypeScript-Entities'
}

{ #category : #testing }
FamixTypeScriptImportingContext >> importAccess [
	<generated>
	^ self import: FamixTypeScriptAccess
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importAttribute [
	<generated>
	^ self import: FamixTypeScriptAttribute
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importClass [
	<generated>
	^ self import: FamixTypeScriptClass
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importComment [
	<generated>
	^ self import: FamixTypeScriptComment
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importContainerEntity [
	<generated>
	^ self import: FamixTypeScriptContainerEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importEntity [
	<generated>
	^ self import: FamixTypeScriptEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importFile [
	<generated>
	^ self import: FamixTypeScriptFile
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importFolder [
	<generated>
	^ self import: FamixTypeScriptFolder
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importFunction [
	<generated>
	^ self import: FamixTypeScriptFunction
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importIndexedFileAnchor [
	<generated>
	^ self import: FamixTypeScriptIndexedFileAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importInheritance [
	<generated>
	^ self import: FamixTypeScriptInheritance
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importInvocation [
	<generated>
	^ self import: FamixTypeScriptInvocation
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importLocalVariable [
	<generated>
	^ self import: FamixTypeScriptLocalVariable
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importMethod [
	<generated>
	^ self import: FamixTypeScriptMethod
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importModule [
	<generated>
	^ self import: FamixTypeScriptModule
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importNamedEntity [
	<generated>
	^ self import: FamixTypeScriptNamedEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importNamespace [
	<generated>
	^ self import: FamixTypeScriptNamespace
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importParameter [
	<generated>
	^ self import: FamixTypeScriptParameter
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importParameterType [
	<generated>
	^ self import: FamixTypeScriptParameterType
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importParameterizableClass [
	<generated>
	^ self import: FamixTypeScriptParameterizableClass
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importParameterizedType [
	<generated>
	^ self import: FamixTypeScriptParameterizedType
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importSourceAnchor [
	<generated>
	^ self import: FamixTypeScriptSourceAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importSourceLanguage [
	<generated>
	^ self import: FamixTypeScriptSourceLanguage
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importSourceTextAnchor [
	<generated>
	^ self import: FamixTypeScriptSourceTextAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importSourcedEntity [
	<generated>
	^ self import: FamixTypeScriptSourcedEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importStructuralEntity [
	<generated>
	^ self import: FamixTypeScriptStructuralEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importType [
	<generated>
	^ self import: FamixTypeScriptType
]

{ #category : #testing }
FamixTypeScriptImportingContext >> importUnknownSourceLanguage [
	<generated>
	^ self import: FamixTypeScriptUnknownSourceLanguage
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportAccess [
	<generated>
	^ self shouldImport: FamixTypeScriptAccess
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportAttribute [
	<generated>
	^ self shouldImport: FamixTypeScriptAttribute
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportClass [
	<generated>
	^ self shouldImport: FamixTypeScriptClass
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportComment [
	<generated>
	^ self shouldImport: FamixTypeScriptComment
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportContainerEntity [
	<generated>
	^ self shouldImport: FamixTypeScriptContainerEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportEntity [
	<generated>
	^ self shouldImport: FamixTypeScriptEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportFile [
	<generated>
	^ self shouldImport: FamixTypeScriptFile
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportFolder [
	<generated>
	^ self shouldImport: FamixTypeScriptFolder
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportFunction [
	<generated>
	^ self shouldImport: FamixTypeScriptFunction
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportIndexedFileAnchor [
	<generated>
	^ self shouldImport: FamixTypeScriptIndexedFileAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportInheritance [
	<generated>
	^ self shouldImport: FamixTypeScriptInheritance
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportInvocation [
	<generated>
	^ self shouldImport: FamixTypeScriptInvocation
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportLocalVariable [
	<generated>
	^ self shouldImport: FamixTypeScriptLocalVariable
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportMethod [
	<generated>
	^ self shouldImport: FamixTypeScriptMethod
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportModule [
	<generated>
	^ self shouldImport: FamixTypeScriptModule
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportNamedEntity [
	<generated>
	^ self shouldImport: FamixTypeScriptNamedEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportNamespace [
	<generated>
	^ self shouldImport: FamixTypeScriptNamespace
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportParameter [
	<generated>
	^ self shouldImport: FamixTypeScriptParameter
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportParameterType [
	<generated>
	^ self shouldImport: FamixTypeScriptParameterType
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportParameterizableClass [
	<generated>
	^ self shouldImport: FamixTypeScriptParameterizableClass
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportParameterizedType [
	<generated>
	^ self shouldImport: FamixTypeScriptParameterizedType
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportSourceAnchor [
	<generated>
	^ self shouldImport: FamixTypeScriptSourceAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportSourceLanguage [
	<generated>
	^ self shouldImport: FamixTypeScriptSourceLanguage
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportSourceTextAnchor [
	<generated>
	^ self shouldImport: FamixTypeScriptSourceTextAnchor
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportSourcedEntity [
	<generated>
	^ self shouldImport: FamixTypeScriptSourcedEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportStructuralEntity [
	<generated>
	^ self shouldImport: FamixTypeScriptStructuralEntity
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportType [
	<generated>
	^ self shouldImport: FamixTypeScriptType
]

{ #category : #testing }
FamixTypeScriptImportingContext >> shouldImportUnknownSourceLanguage [
	<generated>
	^ self shouldImport: FamixTypeScriptUnknownSourceLanguage
]
