Class {
	#name : #FamixTypeScriptMultipleFileAnchor,
	#superclass : #FamixTypeScriptSourceAnchor,
	#traits : 'FamixTMultipleFileAnchor',
	#classTraits : 'FamixTMultipleFileAnchor classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptMultipleFileAnchor class >> annotation [

	<FMClass: #MultipleFileAnchor super: #FamixTypeScriptSourceAnchor>
	<package: #FamixTypeScript>
	<generated>
	^self
]
