Class {
	#name : #FamixTypeScriptIndexedFileAnchor,
	#superclass : #FamixTypeScriptAbstractFileAnchor,
	#traits : 'FamixTIndexedFileNavigation',
	#classTraits : 'FamixTIndexedFileNavigation classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptIndexedFileAnchor class >> annotation [

	<FMClass: #IndexedFileAnchor super: #FamixTypeScriptAbstractFileAnchor>
	<package: #FamixTypeScript>
	<generated>
	^self
]
