Class {
	#name : #FamixTypeScriptSourceLanguage,
	#superclass : #FamixTypeScriptEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptSourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #FamixTypeScriptEntity>
	<package: #FamixTypeScript>
	<generated>
	^self
]
