Class {
	#name : #FamixTypeScriptImportClause,
	#superclass : #FamixTypeScriptAssociation,
	#traits : 'FamixTImport',
	#classTraits : 'FamixTImport classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptImportClause class >> annotation [

	<FMClass: #ImportClause super: #FamixTypeScriptAssociation>
	<package: #FamixTypeScript>
	<generated>
	^ self
]
