Class {
	#name : #FamixTypeScriptSourceTextAnchor,
	#superclass : #FamixTypeScriptSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixTypeScriptSourceAnchor>
	<package: #FamixTypeScript>
	<generated>
	^self
]
