Class {
	#name : #FamixTypeScriptParameterizableClass,
	#superclass : #FamixTypeScriptClass,
	#traits : 'FamixTWithParameterizedTypes',
	#classTraits : 'FamixTWithParameterizedTypes classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptParameterizableClass class >> annotation [

	<FMClass: #ParameterizableClass super: #FamixTypeScriptClass>
	<package: #FamixTypeScript>
	<generated>
	^self
]
