"
I represent a TypeScript implicit variable.
"
Class {
	#name : #FamixTypeScriptimplicitVariable,
	#superclass : #FamixTypeScriptVariable,
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptimplicitVariable class >> annotation [

	<FMClass: #implicitVariable super: #FamixTypeScriptVariable>
	<package: #FamixTypeScript>
	<generated>
	^ self
]
