Class {
	#name : #FamixTypeScriptParameterType,
	#superclass : #FamixTypeScriptType,
	#traits : 'FamixTParameterType',
	#classTraits : 'FamixTParameterType classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptParameterType class >> annotation [

	<FMClass: #ParameterType super: #FamixTypeScriptType>
	<package: #FamixTypeScript>
	<generated>
	^self
]
