"
I represent an abstraction of various entities that have behavior.


"
Class {
	#name : #FamixTypeScriptBehaviouralEntity,
	#superclass : #FamixTypeScriptContainerEntity,
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptBehaviouralEntity class >> annotation [

	<FMClass: #BehaviouralEntity super: #FamixTypeScriptContainerEntity>
	<package: #FamixTypeScript>
	<generated>
	^ self
]
