"
I represent a TypeScript (JavaScript) Doc element.


"
Class {
	#name : 'FamixTypeScriptJSDoc',
	#superclass : 'FamixTypeScriptSourcedEntity',
	#category : 'Famix-TypeScript-Entities-Entities',
	#package : 'Famix-TypeScript-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTypeScriptJSDoc class >> annotation [

	<FMClass: #JSDoc super: #FamixTypeScriptSourcedEntity>
	<package: #FamixTypeScript>
	<generated>
	^ self
]
