"
I represent a TypeScript variable statement.


"
Class {
	#name : #FamixTypeScriptVariableStatement,
	#superclass : #FamixTypeScriptType,
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptVariableStatement class >> annotation [

	<FMClass: #VariableStatement super: #FamixTypeScriptType>
	<package: #FamixTypeScript>
	<generated>
	^ self
]
