Class {
	#name : #FamixTypeScriptInheritance,
	#superclass : #FamixTypeScriptAssociation,
	#traits : 'FamixTInheritance',
	#classTraits : 'FamixTInheritance classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptInheritance class >> annotation [

	<FMClass: #Inheritance super: #FamixTypeScriptAssociation>
	<package: #FamixTypeScript>
	<generated>
	^ self
]
