Class {
	#name : #FamixTypeScriptParameterizableInterface,
	#superclass : #FamixTypeScriptInterface,
	#traits : 'FamixTWithParameterizedTypes',
	#classTraits : 'FamixTWithParameterizedTypes classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptParameterizableInterface class >> annotation [

	<FMClass: #ParameterizableInterface super: #FamixTypeScriptInterface>
	<package: #FamixTypeScript>
	<generated>
	^ self
]
