Class {
	#name : #FamixTypeScriptAbstractFileAnchor,
	#superclass : #FamixTypeScriptSourceAnchor,
	#traits : 'FamixTFileAnchor',
	#classTraits : 'FamixTFileAnchor classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptAbstractFileAnchor class >> annotation [

	<FMClass: #AbstractFileAnchor super: #FamixTypeScriptSourceAnchor>
	<package: #FamixTypeScript>
	<generated>
	^self
]
