"
I represent a TypeScript parametric function.

## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `typeParameters` | `FamixTParametricEntity` | `genericEntity` | `FamixTTypeParameter` | The type parameters of this parametric entity. They can any type with the exception of primitive types|



"
Class {
	#name : 'FamixTypeScriptParametricFunction',
	#superclass : 'FamixTypeScriptFunction',
	#traits : 'FamixTParametricEntity',
	#classTraits : 'FamixTParametricEntity classTrait',
	#category : 'Famix-TypeScript-Entities-Entities',
	#package : 'Famix-TypeScript-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTypeScriptParametricFunction class >> annotation [

	<FMClass: #ParametricFunction super: #FamixTypeScriptFunction>
	<package: #'Famix-TypeScript-Entities'>
	<generated>
]
