Class {
	#name : #FamixTypeScriptPreprocessorDefine,
	#superclass : #FamixTypeScriptPreprocessorStatement,
	#traits : 'FamixTPreprocessorIfdef',
	#classTraits : 'FamixTPreprocessorIfdef classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptPreprocessorDefine class >> annotation [

	<FMClass: #PreprocessorDefine super: #FamixTypeScriptPreprocessorStatement>
	<package: #FamixTypeScript>
	<generated>
	^self
]
