"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `concretizations` | `FamixTParametricAssociation` | `triggeringAssociation` | `FamixTConcretization` | The parameter concretizations associated with this association.|



"
Class {
	#name : 'FamixTypeScriptParametricEntityTyping',
	#superclass : 'FamixTypeScriptEntityTyping',
	#traits : 'FamixTParametricAssociation',
	#classTraits : 'FamixTParametricAssociation classTrait',
	#category : 'Famix-TypeScript-Entities-Entities',
	#package : 'Famix-TypeScript-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTypeScriptParametricEntityTyping class >> annotation [

	<FMClass: #ParametricEntityTyping super: #FamixTypeScriptEntityTyping>
	<package: #'Famix-TypeScript-Entities'>
	<generated>
]
